import re

all_phrases = set()

# 1. From whitesmith_cribs.txt
try:
    with open("whitesmith_cribs.txt") as f:
        for line in f:
            clean = re.sub(r'[^A-Z]', '', line.strip().upper())
            if len(clean) >= 18:
                for i in range(len(clean) - 17):
                    all_phrases.add(clean[i : i + 18])
except Exception as e:
    print("Error reading whitesmith_cribs.txt:", e)

# 2. Key phrases from PK1-PK7
narrative_sources = [
    "INVESTIGATION LOG ITEM EIGHT KNOT TIGHTLY WOUND ITS THREAD INSCRIBED WITH LETTERS THE ACCESSION LOG SAYS ONCE UNRAVELED IT REVEALS THE ROUTE TO THE LOST ARCHIVE OF PELLEGRIN TWELVE PRIOR ARCHIVISTS TRIED TO UNRAVEL IT ALL FAILED",
    "I HAVE FOUND REFERENCES TO THE KNOT IN SEVEN OTHER RECORDS IN OUR ARCHIVE THE MOST INTRIGUING IS A PASSING COMMENT IN A TREATISE ON TEXTILES WRITTEN IN PELLEGRINS OWN HAND WHICH SAYS UN AGO TANTO SOTTILE DA LEGGERE QUALUNQUE NODO I BELIEVED THIS TO BE JUST A TURN OF PHRASE BUT THE OTHER MENTIONS SCATTERED THROUGH MARGINALIA IN BOOKS THAT SHARE NO OTHER TOPIC HAVE LED ME TO SUSPECT THE PASSAGE REFERS TO A REAL OBJECT A NEEDLE",
    "SEVENTH MONTH I WROTE TO FIFTEEN CORRESPONDENTS IN SIX COUNTRIES SEEKING ANY WORD OF THE ITEM MOST KNEW NOTHING A FEW HAD HEARD LEGENDS OF A NEEDLE FINE ENOUGH TO SPLIT A HAIR OR PIERCE GLASS AT LAST A VIENNESE ANATOMIST SAID HE SAW SUCH AN INSTRUMENT USED AT A SURGICAL DEMONSTRATION IN BERN I WROTE TO HIS ADDRESS NO ANSWER CAME I WROTE AGAIN",
    "THE STRINGS MEASURE TWO FURLONGS WE EXAMINED THE WEAVE AND TENSION OF EACH INDIVIDUAL STRAND FINDING MICROSCOPIC CHARACTERS ENGRAVED ALONG ITS ENTIRE LENGTH EACH PULL OF THE THREAD REVEALED FURTHER LETTERS WRITTEN IN SECTIONS RISING IN COMPLEXITY TOWARDS THE CORE",
    "WE EXAMINED THE FIBERS UNDER THE LENS THE FLAX WAS SPUN WITH EXCEPTIONAL PRECISION PRESERVING THE INSCRIPTIONS WITHOUT DISTORTION EACH KNOT CONTAINED A TIGHTLY FOLDED SEQUENCE OF LETTERS WHICH WHEN PROJECTED ONTO THE PLANE FORMED AN INTERLOCKING GRID OF COORDINATES AND CIPHERTEXT WHICH POINTED US DIRECTLY TOWARDS BERN",
    "THE WHITESMITHS WORKSHOP IS FILLED WITH THE OLD TOOLS OF HIS TRADE MY EYES ARE DRAWN TO THE GUTTER ALONG THE WALL WHICH IS STREWN WITH EXQUISITE NEEDLES THE WHITESMITH SAYS HE MAKES ONE EVERY DAY AND LOST COUNT LONG AGO I ASK WHAT HE DOES WITH THEM AND HE SAYS THEY ARE ONLY THE RESIDUE OF HIS PRACTICE HE TELLS ME THAT IF I STUDY UNDER HIM FOR TEN YEARS HE WILL LET ME TAKE ONE OF MY OWN MAKING",
    "HE POINTED TO THE HEARTH AND SAID THAT THE WORK COULD ONLY BEGIN WHEN THE FIRE REACHED ITS PROPER HEAT WITH LONG TONGS HE HELD THE STEEL INTO COALS THAT GLOWED WHITE IN THE BELLOWS WARNING ME THAT ONE MOMENT OF TEMPERING CAN DESTROY YEARS OF LABOUR FOR ONLY AN IRON PIECE PURIFIED NINE DAYS IN THE FLAME WILL HOLD A FINE ENOUGH EDGE TO BE FORGED",
    # Candidate continuations
    "AFTER NINE DAYS IN THE FLAME THE STEEL WAS READY HE DREW THE GLOWING METAL FROM THE HEARTH AND PLACED IT UPON THE ANVIL TO BE FORGED INTO A FINE NEEDLE",
    "FOR NINE DAYS I PUMPED THE BELLOWS AND TENDED THE COALS UNTIL THE WHITE HEAT PURIFIED THE IRON PIECE HE TOOK UP HIS HAMMER AND BEGAN TO FORGE THE NEEDLE",
    "ON THE TENTH DAY HE DREW THE STEEL FROM THE WHITE COALS WITH HIS LONG TONGS AND STRUCK IT WITH HIS HAMMER DRAWING IT OUT INTO A SLENDER WIRE",
    "HE DREW THE PURIFIED STEEL THROUGH THE DRAWPLATE HOLE BY HOLE UNTIL IT WAS AS FINE AS A HAIR THEN FLATTENED THE HEAD AND PUNCHED THE EYE",
    "WITH A SLENDER PUNCH HE PIERCED THE EYE OF THE NEEDLE AND FILED THE EDGES SMOOTH BEFORE TEMPERING THE POINT IN OIL TO HARDEN THE STEEL",
    "HE QUENCHED THE RED HOT NEEDLE IN WATER AND HELD IT TO THE LIGHT A NEEDLE OF MY OWN MAKING FINE ENOUGH TO READ ANY KNOT IN PELLEGRINS ARCHIVE",
    "AT LAST I HELD THE NEEDLE OF MY OWN MAKING IN MY HAND THE RESIDUE OF TEN YEARS OF STUDY AND PRACTICE IN THE WHITESMITHS WORKSHOP",
    "HE SMILED AND HANDED ME THE FINISHED NEEDLE SAYING THAT NOW I WAS READY TO UNRAVEL THE TWELVE KNOTS OF PELLEGRIN AND FIND THE LOST ARCHIVE",
    "NOW HE SAID TAKE UP THE NEEDLE OF YOUR OWN MAKING AND GO TO THE FOOT OF THE SWISS ALPS WHERE THE ARCHIVE OF PELLEGRIN LIES CONCEALED",
    "THE WORK OF MAKING THE NEEDLE WAS COMPLETED AFTER NINE DAYS IN THE FLAME AND TEN YEARS AT THE ANVIL OF THE OLD MASTER WHITESMITH"
]

for text in narrative_sources:
    clean = re.sub(r'[^A-Z]', '', text.upper())
    if len(clean) >= 18:
        for i in range(len(clean) - 17):
            all_phrases.add(clean[i : i + 18])

# 3. From Hendrie Book 3 excerpts
try:
    with open("theophilus_book3_english.txt") as f:
        txt = f.read()
    words = re.findall(r'[A-Z]+', txt.upper())
    clean_book3 = "".join(words)
    # Sample every 5th substring to keep size reasonable
    for i in range(0, len(clean_book3) - 17, 3):
        all_phrases.add(clean_book3[i : i + 18])
except Exception as e:
    print("Error reading theophilus_book3_english.txt:", e)

phrases_list = sorted(list(all_phrases))
print(f"Total compiled craft phrases: {len(phrases_list)}")

with open("craft_phrases_18.txt", "w") as f:
    for p in phrases_list:
        f.write(p + "\n")

print("Saved to craft_phrases_18.txt!")
