# Cracking PK8 via Narrative Forward-Crib Dragging under 4-Clock {4,5,6,7} Quagmire III
import math
from collections import Counter

KRYPTOS = "KRYPTOSABCDEFGHIJLMNQUVWXZ"
PK8_CT = "COPVEJJVSVURTVIPYOTPLHGBTMAUCCPESIWIGZBWSJPKTRPUEKQFIFCLHMXTHIMHWOYIGURBOMPARCVXVKBDDVBVHDRHGCVNWWVLBMYWMWHICFIXZWBVZYCQGNOGJGUMLNPUTHQCXNWPQZOIRJZGSWVPY"
N = len(PK8_CT) # 153

print("==========================================================================================")
print("             PK8 (153 CHARS) NARRATIVE FORWARD-CRIB CRACKING ENGINE                       ")
print("==========================================================================================\n")
print(f"PK8 Ciphertext (N = {N}):\n{PK8_CT}\n")

# Proven binary parity vectors for PK8 clocks:
q7_parity = [0, 1, 1, 1, 0, 0, 0]

# Candidate narrative sentences continuing from PK7:
# PK7 ended with: "...FOR ONLY AN IRON PIECE PURIFIED NINE DAYS IN THE FLAME WILL HOLD A FINE ENOUGH EDGE TO BE FORGED"
candidate_openings = [
    "ONTHETENTHDAYHEDREWTHESTEELFROMTHEFLAME",
    "ONTHETENTHDAYTHEFIREWASQUENCHEDANDTHE",
    "FORNINEDAYSTHEBELLOWSROAREDANDTHECOALS",
    "ATLASTTHENINEDAYSPASSEDANDHEDREWTHEIRON",
    "THEMASTERTOOKUPHISHAMMERANDSTRUCKTHE",
    "WITHLONGTONGSHEDREWTHEGLOWINGIRONFROM",
    "HELAIDTHEGLOWINGSTEELUPONTHEANVILAND",
    "EACHBLOWOFTHEHAMMERDREWTHEMETALTHINNER",
    "NOWHESAIDTHESTEELISREADYFORANVILAND",
    "THENINTHDAYDAWNEDANDTHECOALSTURNEDWHITE",
    "ATLASTTHECOALSTURNEDWHITEANDTHEMASTER",
    "THENINEDAYSBEINGFULFILLEDHEDREWTHESTEEL",
    "WITHCAREHEPLACEDTHEGLOWINGSTEELUPONTHE",
    "HETURNEDFROMTHEHEARTHANDTOOKUPHISHAMMER",
    "THEBELLOWSSANGANDTHECOALSTURNEDWHITEAS",
    "HEDREWTHEGLOWINGRODFROMTHEWHITECOALSAND",
    "THEANVILRANGWITHEACHBLOWOFTHEHAMMERAS",
    "FORNINEDAYSANDNINENIGHTSTHEBELLOWSROARED",
    "THESTEELWASREADYANDTHEMASTERBEGANTOSTRIKE"
]

print(f"Loaded {len(candidate_openings)} candidate narrative openings for PK8.\n")

# For each candidate opening, check if it can be generated by 4 clocks {4, 5, 6, 7}:
# In an additive clock system: C[i] - P[i] = q4[i%4] + q5[i%5] + q6[i%6] + q7[i%7] (mod 26).
# If a crib has length L >= 22 (the number of clock variables), we can test consistency!

def test_crib_consistency(crib, start_pos=0):
    L = len(crib)
    shifts = {}
    for i in range(L):
        pos = start_pos + i
        ct_char = PK8_CT[pos]
        pt_char = crib[i]
        c_idx = KRYPTOS.index(ct_char)
        p_idx = KRYPTOS.index(pt_char)
        s = (c_idx - p_idx + 26) % 26
        shifts[pos] = s
        
    # Solve system of linear equations over Z_26:
    # s[pos] = q4[pos%4] + q5[pos%5] + q6[pos%6] + q7[pos%7] (mod 26)
    # Check if a solution exists!
    import z3
    solver = z3.Solver()
    
    q4 = [z3.Int(f"q4_{i}") for i in range(4)]
    q5 = [z3.Int(f"q5_{i}") for i in range(5)]
    q6 = [z3.Int(f"q6_{i}") for i in range(6)]
    q7 = [z3.Int(f"q7_{i}") for i in range(7)]
    
    for v in q4 + q5 + q6 + q7:
        solver.add(v >= 0, v < 26)
        
    # Parity constraints from q7_parity:
    for i in range(7):
        solver.add(q7[i] % 2 == q7_parity[i])
        
    for pos, s in shifts.items():
        solver.add((q4[pos%4] + q5[pos%5] + q6[pos%6] + q7[pos%7]) % 26 == s)
        
    if solver.check() == z3.sat:
        m = solver.model()
        sol_q4 = [m[v].as_long() for v in q4]
        sol_q5 = [m[v].as_long() for v in q5]
        sol_q6 = [m[v].as_long() for v in q6]
        sol_q7 = [m[v].as_long() for v in q7]
        return True, (sol_q4, sol_q5, sol_q6, sol_q7)
    return False, None

# Test z3 availability
try:
    import z3
    has_z3 = True
except ImportError:
    has_z3 = False
    print("Z3 solver not installed; will test via integer linear programming or C solver.")
