#!/usr/bin/env python3
"""Generate PK9 openings centered on the return journey and archive arrival."""
from itertools import product
from pathlib import Path
import argparse
import re

SUBJECTS = (
 "I", "WE", "HE", "THE ARCHIVIST", "THE APPRENTICE", "THE TRAVELLER",
 "THE ARCHIVE", "THE OLD ARCHIVE", "THE LOST ARCHIVE", "THE BUILDING",
 "THE DOOR", "THE DOORS", "THE GATE", "THE HALL", "THE HALLS", "THE CORRIDOR",
 "THE ROOM", "THE RECORDS", "THE KNOT", "THE THREAD", "THE STRING",
 "THE NEEDLE", "THE WHITESMITHS NEEDLE", "MY NEEDLE", "MY HAND", "MY HANDS",
 "THE LETTER", "DAWN", "MORNING", "THE NIGHT", "THE MOON", "THE ROAD",
 "THE JOURNEY", "THE RETURN JOURNEY", "THE ROUTE", "THE PATH", "THE WAY",
)
VERBS = (
 "ARRIVE", "ARRIVED", "RETURN", "RETURNED", "REACH", "REACHED", "COME", "CAME",
 "WALK", "WALKED", "TRAVEL", "TRAVELLED", "FOLLOW", "FOLLOWED", "TAKE", "TOOK",
 "CARRY", "CARRIED", "HOLD", "HELD", "KEEP", "KEPT", "HIDE", "HID", "ENTER",
 "ENTERED", "UNLOCK", "UNLOCKED", "OPEN", "OPENED", "CLOSE", "CLOSED", "PASS",
 "PASSED", "DESCEND", "DESCENDED", "CLIMB", "CLIMBED", "CROSS", "CROSSED",
 "FIND", "FOUND", "SEE", "SAW", "APPROACH", "APPROACHED", "LEAVE", "LEFT",
 "WAIT", "WAITED", "REST", "RESTED", "KNEEL", "KNELT", "SIT", "SAT", "STAND",
 "STOOD", "BEGIN", "BEGAN", "START", "STARTED", "PLACE", "PLACED", "LAY", "LAID",
 "SET", "INSERT", "INSERTED", "PUSH", "PUSHED", "DRAW", "DREW", "PULL", "PULLED",
 "PIERCE", "PIERCED", "PRICK", "PRICKED", "TOUCH", "TOUCHED", "CUT", "CUTS",
 "SPLIT", "SPLITS", "UNTIE", "UNTIED", "LOOSEN", "LOOSENED", "UNRAVEL", "UNRAVELED",
 "OPENS", "WAITS", "LIES", "REMAINS", "BEGINS", "YIELDS", "PARTS", "BREAKS",
 "LEADS", "POINTS", "REVEALS", "SHOWS", "FITS", "SLIDES", "MOVES", "TURNS",
)
OBJECTS = (
 "AT DAWN", "BEFORE DAWN", "BY DAWN", "AFTER MIDNIGHT", "BEFORE SUNRISE",
 "AT THE ARCHIVE", "BEFORE THE ARCHIVE", "OUTSIDE THE ARCHIVE", "INSIDE THE ARCHIVE",
 "TO THE ARCHIVE", "TOWARDS THE ARCHIVE", "THROUGH THE NIGHT", "ALL NIGHT",
 "ALONG THE ROAD", "ALONG THE ROUTE", "ALONG THE PATH", "BACK TO THE ARCHIVE",
 "THE ARCHIVE", "THE ARCHIVE DOOR", "THE DOOR", "THE OLD DOOR", "THE GATE",
 "THE DARK HALL", "THE EMPTY HALL", "THE CORRIDOR", "THE STAIRS", "THE ROOM",
 "THE RECORDS", "THE OLD RECORDS", "THE INVESTIGATION LOG", "THE KNOT",
 "THE ANCIENT KNOT", "THE TIGHT KNOT", "THE THREAD", "THE STRING", "THE FIRST THREAD",
 "THE NEEDLE", "THE STOLEN NEEDLE", "THE WHITESMITHS NEEDLE", "ONE NEEDLE",
 "THE POINT", "THE NEEDLE POINT", "THE EYE", "THE LETTER", "MY SHORT LETTER",
 "IN MY HAND", "WITH THE NEEDLE", "WITH ONE NEEDLE", "WITH THE KNOT BEFORE ME",
 "UNDER THE LAMP", "BENEATH THE LAMP", "UNDER THE LENS", "IN THE DARK",
 "IN SILENCE", "WITHOUT A SOUND", "FOR THE LAST TIME", "ONCE MORE",
)
LEADS = (
 "AT DAWN", "BEFORE DAWN", "BY DAWN", "NEAR DAWN", "AFTER MIDNIGHT",
 "BEFORE SUNRISE", "AS DAWN BREAKS", "AS MORNING COMES", "WHEN MORNING COMES",
 "THROUGH THE NIGHT", "ALL THROUGH THE NIGHT", "HOURS LATER", "AN HOUR LATER",
 "BEFORE THE SUN RISES", "WHILE THE CITY SLEEPS", "UNDER THE MOON",
 "IN THE DARK", "IN SILENCE", "WITHOUT A SOUND", "AT LAST", "ONCE MORE",
 "WHEN I ARRIVE", "WHEN I ARRIVED", "WHEN I RETURN", "WHEN I RETURNED",
 "WHEN I REACH THE ARCHIVE", "UPON MY RETURN", "ON MY RETURN", "AFTER I RETURN",
 "AFTER I RETURNED", "BACK AT THE ARCHIVE", "AT THE ARCHIVE", "INSIDE THE ARCHIVE",
 "OUTSIDE THE ARCHIVE", "WITH THE NEEDLE", "WITH ONE NEEDLE", "NEEDLE IN HAND",
)
CLAUSES = (
 "I ARRIVE", "I ARRIVED", "I REACH THE ARCHIVE", "I REACHED THE ARCHIVE",
 "I RETURN TO THE ARCHIVE", "I RETURNED TO THE ARCHIVE", "I AM BACK AT THE ARCHIVE",
 "I COME TO THE ARCHIVE", "I CAME TO THE ARCHIVE", "I ENTER THE ARCHIVE",
 "I ENTERED THE ARCHIVE", "I OPEN THE ARCHIVE DOOR", "I UNLOCK THE DOOR",
 "I WALK THROUGH THE NIGHT", "I TRAVEL THROUGH THE NIGHT", "I FOLLOW THE OLD ROAD",
 "I FOLLOW THE ROUTE", "I CARRY THE NEEDLE", "I HOLD THE NEEDLE IN MY HAND",
 "I TAKE OUT THE NEEDLE", "I FIND THE KNOT", "I STAND BEFORE THE KNOT",
 "I KNEEL BEFORE THE KNOT", "I PLACE THE NEEDLE", "I INSERT THE NEEDLE",
 "I TOUCH THE KNOT", "I PIERCE THE KNOT", "I BEGIN TO UNRAVEL THE KNOT",
 "THE ARCHIVE IS DARK", "THE ARCHIVE IS SILENT", "THE ARCHIVE IS EMPTY",
 "THE ARCHIVE DOOR IS LOCKED", "THE HALLS ARE EMPTY", "THE HALL IS SILENT",
 "THE KNOT IS WHERE I LEFT IT", "THE KNOT LIES BEFORE ME", "THE KNOT WAITS",
 "THE NEEDLE IS COLD", "THE NEEDLE FITS", "THE NEEDLE POINT IS FINE",
 "NO ONE SEES ME", "NO ONE IS THERE", "EVERYTHING IS SILENT", "DAWN IS NEAR",
)
FIXED = (
 "THE JOURNEY TO THE ARCHIVE TAKES THE REST OF THE NIGHT",
 "THE RETURN JOURNEY TAKES THE REST OF THE NIGHT",
 "I REACH THE ARCHIVE JUST BEFORE DAWN",
 "I RETURN TO THE ARCHIVE BEFORE DAWN",
 "BY DAWN I AM BACK AT THE ARCHIVE",
 "THE ARCHIVE IS DARK AND SILENT WHEN I ARRIVE",
 "THE KNOT IS WAITING WHERE I LEFT IT",
 "I HOLD THE WHITESMITHS NEEDLE IN MY HAND",
 "WITH THE NEEDLE IN MY HAND I APPROACH THE KNOT",
 "NO ONE SEES ME ENTER THE ARCHIVE",
 "THE DOOR OPENS WITHOUT A SOUND",
 "I HAVE NOT SEEN THE KNOT FOR TEN YEARS",
 "INVESTIGATION LOG ITEM NINE",
)
def norm(x): return re.sub('[^A-Z]','',x.upper())
def main():
 parser=argparse.ArgumentParser(description=__doc__)
 parser.add_argument('output',nargs='?',default='/tmp/pk9_return18.txt')
 parser.add_argument('--length',type=int,default=18)
 args=parser.parse_args()
 length=args.length; out=set()
 def add(x):
  x=norm(x)
  if len(x)>=length:out.add(x[:length])
 for x in FIXED:add(x)
 for s,v,o in product(SUBJECTS,VERBS,OBJECTS):add(f'{s} {v} {o}')
 for lead,clause in product(LEADS,CLAUSES):add(f'{lead} {clause}')
 for lead,s,v in product(LEADS,("I","WE","THE ARCHIVIST","THE KNOT","THE NEEDLE"),VERBS):add(f'{lead} {s} {v}')
 path=Path(args.output)
 path.write_text('\n'.join(sorted(out))+'\n');print(f'wrote {len(out):,} openings')
if __name__=='__main__':main()
