import re

sources = []

# PK1, PK2, PK3, PK6 texts
with open("paradigm_kryptos_cryptanalytic_report.md") as f:
    text = f.read()
    # extract plaintexts
    caps = re.findall(r'[A-Z]{12,}', text)
    sources.extend(caps)

# Theophilus text
with open("theophilus_hendrie.txt") as f:
    t_text = f.read().upper()
    t_words = re.findall(r'[A-Z]+', t_text)
    sources.append("".join(t_words))

# Thematic Italian & English phrases
extra = [
    "UNAGOTANTOSOTTILEDALEGGEREQUALUNQUENODO",
    "TANTOSOTTILEDALEGGEREQUALUNQUENODO",
    "UNAGOTANTOSOTTILEDALEGGERE",
    "LEGGEREQUALUNQUENODO",
    "ANEEDLESOTHINASTOREADANYKNOT",
    "NEEDLESOTHINASTOREADANYKNOT",
    "ANEEDLEFINEENOUGHTOSPLITAHAIR",
    "FINEENOUGHTOSPLITAHAIR",
    "ORPIERCEGLASSSURGICAL",
    "SURGICALDEMONSTRATIONINBERN",
    "THEWHITESMITHSWORKSHOPISFILLEDWITH",
    "THEOLDTOOLSOFHISTRADE",
    "MYEYESAREDRAWNTOTHEGUTTER",
    "ALONGTHEWALLWHICHISSTREWNWITH",
    "EXQUISITENEEDLESTHEWHITESMITH",
    "SAYSHEMAKESONEEVERYDAY",
    "ANDLOSTCOUNTLONGAGOIASKWHAT",
    "HEDOESWITHTHEMANDHESAYS",
    "THEYAREONLYTHERESIDUEOFHIS",
    "RESIDUEOFHISPRACTICE",
    "HETELLSMETHATIFISTUDYUNDER",
    "IFISTUDYUNDERHIMFORTENYEARS",
    "STUDYUNDERHIMFORTENYEARS",
    "FORTENYEARSHEWILLLETMETAKE",
    "HEWILLLETMETAKEONEOFMYOWNMAKING",
    "ONEOFMYOWNMAKING",
    "THENEEDLEOFMYOWNMAKING",
    "ANEEDLEOFMYOWNMAKING",
    "FORTENYEARSIWORKEDUNDERHIM",
    "AFTERTENYEARSIFINISHED",
    "AFTERTENYEARSOFPRACTICE",
    "ATLASTTHENEEDLEWASFINISHED",
    "ATLASTIMADEANEEDLEOFMYOWNMAKING",
    "IMADEANEEDLEOFMYOWNMAKING",
    "ITOKTHENEEDLEOFMYOWNMAKING",
    "IRETURNEDTOTHEARCHIVEWITH",
    "RETURNEDTOTHEARCHIVEWITH",
    "THELOSTARCHIVEOFPELLEGRIN",
    "ROUTE TOTHELOSTARCHIVEOF",
    "UNRAVELEDITREVEALSTHEROUTE",
    "INVESTIGATIONLOGITEMEIGHT",
    "INVESTIGATIONLOGITEMNINE",
    "INVESTIGATIONLOGITEMTEN",
    "TWELVEPRIORARCHIVISTSTRIED",
    "PELLEGRINSWORKSHOPWASFOUND",
    "IPIERCEDTHEKNOTWITHTHENEEDLE",
    "PIERCEDTHEKNOTWITHTHENEEDLE",
    "THEKNOTBEGANTOUNRAVEL",
    "UNRAVELEDTHEKNOTANDREAD",
    "THELETTERSINSCRIBEDUPON",
    "THELETTERSINSCRIBEDONTHE",
    "DRAWINGTHEWIRETHROUGHTHE",
    "DRAWTHROUGHTHEDRAWPLATE",
    "HEATEDINTHEFORGEANDQUENCHED",
    "HARDENEDINTHEQUENCHAND",
    "TEMPEREDINTHECHARCOAL",
    "POLISHEDWITHEMERYAND",
    "THEEYEOFTTHENEEDLEWASPIERCED",
    "PIERCINGTHEEYEOFTTHENEEDLE",
    "FINERTHANAHAIRORPIERCEGLASS"
]

sources.extend(extra)

# Generate unique slices of length 16
cribs16 = set()
for src in sources:
    clean = re.sub(r'[^A-Z]', '', src)
    if len(clean) >= 16:
        for i in range(len(clean) - 15):
            cribs16.add(clean[i:i+16])

print(f"Total unique 16-character cribs generated: {len(cribs16)}")

with open("cribs_len16.txt", "w") as f:
    for c in sorted(cribs16):
        f.write(c + "\n")

print("Saved cribs_len16.txt successfully.")
