import itertools, re

def build_expanded_grammar():
    phrases = set()

    # Category 1: "ON THE TENTH DAY...", "AFTER NINE DAYS...", "FOR NINE DAYS..."
    openers_time = [
        "ON THE TENTH DAY", "ON THE ELEVENTH DAY", "ON THE FIRST DAY", "ON THE NINTH DAY",
        "AFTER NINE DAYS", "AFTER THE NINE DAYS", "AFTER NINE DAYS OF", "AFTER NINE DAYS IN",
        "FOR NINE DAYS", "FOR NINE DAYS AND", "FOR NINE DAYS HE", "FOR NINE DAYS WE",
        "FOR NINE DAYS I", "FOR NINE DAYS THE", "DURING THE NINE DAYS", "THROUGH THE NINE DAYS",
        "AT THE END OF NINE DAYS", "WHEN NINE DAYS HAD PASSED", "WHEN THE NINE DAYS HAD PASSED",
        "WHEN THE NINE DAYS WERE OVER", "WHEN THE NINE DAYS WERE ENDED", "THE NINE DAYS PASSED",
        "FOR TEN YEARS", "FOR TEN YEARS I", "FOR TEN YEARS HE", "FOR TEN YEARS WE",
        "AFTER TEN YEARS", "AFTER TEN YEARS I", "AFTER TEN YEARS OF", "DURING TEN YEARS OF",
        "TEN YEARS PASSED", "TEN YEARS OF LABOUR", "TEN YEARS OF PRACTICE", "TEN YEARS OF STUDY"
    ]
    actions_time = [
        "HE DREW THE STEEL FROM THE FIRE", "HE DREW THE STEEL FROM THE FLAME", "HE DREW THE STEEL FROM THE COALS",
        "HE DREW THE STEEL FROM THE HEARTH", "HE DREW THE METAL FROM THE FIRE", "HE DREW THE METAL FROM THE FLAME",
        "HE PULLED THE STEEL FROM THE FIRE", "HE PULLED THE STEEL FROM THE FLAME", "HE PULLED THE STEEL FROM THE COALS",
        "HE TOOK THE STEEL FROM THE FIRE", "HE TOOK THE STEEL FROM THE FLAME", "HE TOOK THE STEEL FROM THE COALS",
        "HE REMOVED THE STEEL FROM THE FIRE", "HE WITHDREW THE STEEL FROM THE FIRE", "HE LIFTED THE STEEL FROM THE FIRE",
        "HE PLACED THE STEEL UPON THE ANVIL", "HE LAID THE STEEL UPON THE ANVIL", "HE SET THE STEEL UPON THE ANVIL",
        "HE TOOK UP HIS HAMMER AND BEGAN", "HE TOOK UP THE HAMMER AND BEGAN", "HE TOOK HIS HAMMER IN HIS HAND",
        "HE TOOK THE TONGS AND LIFTED THE", "HE HELD THE TONGS WITH BOTH HANDS", "HE STRUCK THE GLOWING METAL WITH",
        "HE STRUCK THE STEEL UPON THE ANVIL", "HE BEAT THE GLOWING STEEL WITH HIS", "HE BEGAN TO DRAW THE WIRE THROUGH",
        "HE BEGAN TO FORGE THE NEEDLE UPON", "HE BEGAN THE WORK OF FORGING THE", "THE WORK OF FORGING AT LAST BEGAN",
        "THE WORK OF MAKING THE NEEDLE BEGAN", "WE WERE READY TO FORGE THE NEEDLE", "I WAS READY TO FORGE MY NEEDLE",
        "HE TOLD ME THAT THE WORK COULD BEGIN", "HE SAID THAT THE TIME HAD COME TO", "HE TURNED TO THE ANVIL AND TOOK UP"
    ]
    for o in openers_time:
        for a in actions_time:
            phrases.add(f"{o} {a}")

    # Category 2: Direct Whitesmith Actions ("HE DREW...", "HE TOOK...", "HE PLACED...")
    subjects = ["HE", "THE SMITH", "THE MASTER", "THE WHITESMITH", "MY MASTER"]
    v_pairs = [
        ("DREW THE STEEL FROM THE FIRE", "AND LAID IT UPON THE ANVIL"),
        ("DREW THE STEEL FROM THE COALS", "WITH HIS LONG TONGS AND LAID IT"),
        ("DREW THE GLOWING STEEL FROM THE", "HEARTH AND PLACED IT ON THE ANVIL"),
        ("PULLED THE STEEL FROM THE WHITE", "COALS AND STRUCK IT WITH HIS HAMMER"),
        ("TOOK THE GLOWING METAL FROM THE", "HEARTH AND LAID IT UPON THE ANVIL"),
        ("PLACED THE GLOWING STEEL UPON THE", "ANVIL AND TOOK UP HIS HEAVY HAMMER"),
        ("LAID THE WHITE HOT STEEL UPON THE", "ANVIL AND BEGAN TO BEAT IT INTO WIRE"),
        ("STRUCK THE GLOWING STEEL WITH HIS", "HAMMER DRAWING IT OUT INTO A LONG ROD"),
        ("BEAT THE PURIFIED STEEL UPON THE", "ANVIL SHAPING IT INTO A SLENDER ROD"),
        ("HAMMERED THE STEEL UNTIL IT WAS", "DRAWN INTO A THIN ROUND WIRE"),
        ("DREW THE WIRE THROUGH THE FIRST", "HOLE OF THE STEEL DRAWPLATE UPON THE BENCH"),
        ("DREW THE STEEL THROUGH GRADUATED", "HOLES IN THE DRAWPLATE UNTIL IT WAS THIN"),
        ("PULLED THE WIRE THROUGH SMALLER", "AND SMALLER HOLES UNTIL IT WAS AS FINE"),
        ("FLATTENED ONE END OF THE WIRE", "AND PUNCHED THE EYE WITH A FINE PUNCH"),
        ("PUNCHED THE EYE OF THE NEEDLE", "WITH A SLENDER CHISEL UPON THE ANVIL"),
        ("PIERCED THE EYE WITH A SLENDER", "PUNCH AND FILED THE EDGES SMOOTH"),
        ("TEMPERED THE NEEDLE IN THE OIL", "AFTER HEATING IT TO A CHERRY RED HEAT"),
        ("QUENCHED THE HOT NEEDLE IN WATER", "TO HARDEN THE FINE POINT AND EYE"),
        ("SMILED AND HANDED ME THE FINISHED", "NEEDLE OF MY OWN MAKING AT LAST")
    ]
    for s in subjects:
        for v1, v2 in v_pairs:
            phrases.add(f"{s} {v1} {v2}")

    # Category 3: First-Person Apprentice Narrative ("I TOOK...", "I WATCHED...", "I WORKED...")
    first_person = [
        "I TOOK THE HAMMER IN MY HAND AND", "I HELD THE TONGS WITH BOTH HANDS AND",
        "I WATCHED AS HE DREW THE STEEL FROM", "I WATCHED EVERY MOVEMENT AS HE FORGED",
        "I STOOD BESIDE HIM AT THE FORGE AS", "I PUMPED THE BELLOWS UNTIL THE COALS",
        "I TENDED THE FIRE FOR NINE DAYS AS", "I WORKED AS HIS APPRENTICE FOR TEN",
        "FOR TEN YEARS I STUDIED HIS CRAFT AND", "EACH DAY FOR TEN YEARS I WATCHED HIM",
        "DAY AFTER DAY I WORKED AT THE ANVIL", "DAY BY DAY HE TAUGHT ME THE SECRETS",
        "HE HANDED ME THE HAMMER AND TOLD ME", "HE TOLD ME TO TAKE UP THE TONGS AND",
        "HE SHOWED ME HOW TO DRAW THE WIRE", "HE SHOWED ME HOW TO PUNCH THE EYE OF",
        "NOW HE SAID TAKE THE HAMMER AND BEGIN", "NOW HE SAID IT IS TIME FOR YOU TO FORGE",
        "THIS HE SAID IS THE SECRET OF THE NEEDLE", "THIS NEEDLE HE SAID WILL READ ANY KNOT"
    ]
    fp_conts = [
        "AND STRUCK THE GLOWING METAL", "AND DREW THE STEEL FROM THE FIRE",
        "AND PLACED IT UPON THE ANVIL", "AND BEGAN TO FORGE THE NEEDLE",
        "UNTIL THE WORK WAS FINISHED", "OF MY OWN MAKING AT LAST",
        "TO READ THE LOST ARCHIVE OF PELLEGRIN"
    ]
    for fp in first_person:
        for c in fp_conts:
            phrases.add(f"{fp} {c}")

    # Category 4: Thematic Tool Combinations ("WITH LONG TONGS...", "UPON THE ANVIL...")
    openers_tools = [
        "WITH LONG TONGS HE DREW THE STEEL", "WITH HIS TONGS HE PULLED THE METAL",
        "WITH A HEAVY HAMMER HE STRUCK THE", "WITH A SLENDER HAMMER HE BEAT THE",
        "UPON THE ANVIL HE LAID THE GLOWING", "UPON THE FACE OF THE ANVIL HE STRUCK",
        "ON THE ANVIL HE BEGAN TO SHAPE THE", "IN THE WHITE HEAT OF THE HEARTH HE",
        "FROM THE GLOWING COALS HE WITHDREW", "FROM THE WHITE COALS HE DREW THE STEEL",
        "THROUGH THE DRAWPLATE HE PULLED THE", "THROUGH SMALLER HOLES HE DREW THE WIRE"
    ]
    for ot in openers_tools:
        for a in actions_time[:10]:
            phrases.add(f"{ot} {a}")

    # Clean and extract 18-char prefixes
    cleaned = set()
    for ph in phrases:
        s = re.sub(r'[^A-Z]', '', ph.upper())
        if len(s) >= 18:
            cleaned.add(s[:18])

    return cleaned

cribs = build_expanded_grammar()
print(f"Total unique 18-character expanded candidates: {len(cribs)}")

with open("pk8_expanded_cribs.txt", "w") as f:
    for c in sorted(cribs):
        f.write(c + "\n")

print("Saved to pk8_expanded_cribs.txt")
