#!/usr/bin/env python3
"""Broad natural openings if PK9 is the short letter mentioned by PK8."""
from itertools import product
from pathlib import Path
import argparse
import re
SALUTATIONS=("","MASTER","TEACHER","MY MASTER","MY TEACHER","DEAR MASTER","DEAR TEACHER","MY DEAR MASTER","MY DEAR TEACHER","WHITESMITH","DEAR WHITESMITH","TO MY MASTER","TO MY TEACHER","TO THE WHITESMITH","MY FRIEND","DEAR FRIEND")
OPENERS=(
 "FORGIVE ME","PLEASE FORGIVE ME","I ASK YOUR FORGIVENESS","I HOPE YOU CAN FORGIVE ME","I HOPE YOU WILL FORGIVE ME",
 "I AM SORRY","I AM DEEPLY SORRY","I MUST APOLOGIZE","I OWE YOU AN APOLOGY","DO NOT BE ANGRY","DO NOT THINK ME UNGRATEFUL",
 "PLEASE UNDERSTAND","YOU MUST UNDERSTAND","I HOPE YOU UNDERSTAND","YOU WILL NOT UNDERSTAND","I CANNOT EXPLAIN",
 "BY THE TIME YOU READ THIS","WHEN YOU READ THIS","IF YOU READ THIS","WHEN YOU FIND THIS LETTER","BY THE TIME YOU FIND THIS",
 "I WRITE TO SAY FAREWELL","I WRITE TO SAY GOODBYE","I WRITE TO THANK YOU","I WRITE TO EXPLAIN","I LEAVE THIS LETTER",
 "THIS IS MY FAREWELL","THIS LETTER IS MY FAREWELL","THESE ARE MY LAST WORDS","I HAVE MADE MY CHOICE","MY CHOICE IS MADE",
 "I COULD NOT SAY GOODBYE","I COULD NOT FACE YOU","I COULD NOT TELL YOU","I COULD NOT STAY","I CANNOT STAY",
 "THANK YOU","I THANK YOU","I AM GRATEFUL","I OWE YOU EVERYTHING","YOU HAVE BEEN KIND TO ME","YOU HAVE TAUGHT ME WELL",
 "YOUR PATIENCE HAS TAUGHT ME","YOUR LESSONS HAVE PREPARED ME","I WILL NEVER FORGET YOUR LESSONS","TEN YEARS WOULD NOT BE ENOUGH",
 "I HAVE LEFT","I AM GONE","I WILL BE GONE","I MUST LEAVE","I HAD TO LEAVE","I CHOSE TO LEAVE","I LEAVE AT MIDNIGHT",
 "I HAVE LEFT THE WORKSHOP","I HAVE GONE HOME","I AM GOING HOME","I MUST RETURN HOME","I HAVE RETURNED TO THE ARCHIVE",
 "I AM RETURNING TO THE ARCHIVE","I MUST RETURN TO THE ARCHIVE","I HAVE GONE TO THE ARCHIVE","I AM GOING TO THE ARCHIVE",
 "THE ARCHIVE CALLS ME","THE ARCHIVE NEEDS ME","THE ARCHIVE IS MY CALLING","THE KNOT AWAITS ME","THE KNOT STILL AWAITS",
 "I HAVE TAKEN A NEEDLE","I HAVE TAKEN ONE NEEDLE","I TOOK A NEEDLE","I TOOK ONE NEEDLE","I STOLE A NEEDLE","I BORROWED A NEEDLE",
 "YOU TOLD ME I COULD TAKE ONE","I KNOW I HAVE NO RIGHT","THE NEEDLE IS WITH ME","I NEED THE NEEDLE","I WILL RETURN THE NEEDLE",
)
STATEMENTS=(
 "I HAVE LEFT","I AM GONE","I MUST LEAVE","I COULD NOT STAY","I CANNOT STAY","I HAVE GONE HOME","I AM GOING HOME",
 "I HAVE RETURNED TO THE ARCHIVE","I AM RETURNING TO THE ARCHIVE","I MUST RETURN TO THE ARCHIVE","I GO BACK TO THE ARCHIVE",
 "THE ARCHIVE IS MY TRUE CALLING","THE ARCHIVE HAS ALWAYS BEEN MY CALLING","MY PLACE IS AT THE ARCHIVE","THE KNOT AWAITS ME",
 "I MUST FINISH MY WORK","I MUST FACE THE KNOT","I MUST UNRAVEL THE KNOT","I WILL UNRAVEL THE KNOT","I KNOW WHAT I MUST DO",
 "I HAVE TAKEN ONE NEEDLE","I TOOK ONE NEEDLE FROM THE GUTTER","I HAVE BORROWED A NEEDLE","THE NEEDLE IS WITH ME",
 "I AM GRATEFUL TO YOU","I WILL ALWAYS BE GRATEFUL","I OWE YOU EVERYTHING","YOU HAVE TAUGHT ME WELL","I WILL REMEMBER YOU",
 "DO NOT FOLLOW ME","DO NOT SEARCH FOR ME","PLEASE DO NOT FOLLOW","I WILL NOT RETURN","WE WILL NOT MEET AGAIN",
 "FAREWELL","GOODBYE","THANK YOU","PLEASE FORGIVE ME",
)
CONNECTORS=("","BUT","AND","YET","FOR","BECAUSE","ALTHOUGH","EVEN THOUGH","I KNOW THAT","YOU KNOW THAT","PLEASE KNOW THAT")
FIXED=(
 "MASTER FORGIVE ME FOR LEAVING WITHOUT SAYING GOODBYE",
 "TEACHER I AM SORRY I COULD NOT SAY GOODBYE",
 "MY DEAR TEACHER BY THE TIME YOU READ THIS I WILL BE GONE",
 "FORGIVE ME I HAVE TAKEN ONE NEEDLE FROM THE GUTTER",
 "YOU TOLD ME I COULD TAKE ONE OF MY OWN MAKING",
 "I KNOW THIS NEEDLE IS NOT OF MY OWN MAKING",
 "I MUST BORROW ONE NEEDLE TO FINISH THE WORK I BEGAN",
 "THANK YOU FOR ALL THAT YOU HAVE TAUGHT ME",
 "I AM GRATEFUL FOR YOUR PATIENCE AND YOUR LESSONS",
 "THE ARCHIVE IS MY TRUE CALLING AND THE KNOT AWAITS",
 "I RETURN TO THE ARCHIVE WITH ONE OF YOUR NEEDLES",
 "DO NOT FOLLOW ME THE KNOT IS MINE TO UNRAVEL",
)
def norm(s):return re.sub('[^A-Z]','',s.upper())
def main():
 parser=argparse.ArgumentParser(description=__doc__)
 parser.add_argument('output',nargs='?',default='/tmp/pk9_letter18.txt')
 parser.add_argument('--length',type=int,default=18)
 args=parser.parse_args()
 out=set();n=args.length
 def add(s):
  s=norm(s)
  if len(s)>=n:out.add(s[:n])
 for s in FIXED:add(s)
 for a,b in product(SALUTATIONS,OPENERS):add(a+' '+b)
 for a,b,c in product(SALUTATIONS,OPENERS,STATEMENTS):add(a+' '+b+' '+c)
 for a,b,c in product(OPENERS,CONNECTORS,STATEMENTS):add(a+' '+b+' '+c)
 for a,b,c in product(SALUTATIONS,STATEMENTS,STATEMENTS):add(a+' '+b+' '+c)
 p=Path(args.output);p.write_text('\n'.join(sorted(out))+'\n');print(f'wrote {len(out):,}')
if __name__=='__main__':main()
