#!/usr/bin/env python3
"""Generate natural short-letter opening cribs motivated by PK8's ending."""

import argparse
import itertools
import re

parser = argparse.ArgumentParser()
parser.add_argument("output")
parser.add_argument("--length", type=int, default=30)
args = parser.parse_args()
if args.length < 16:
    parser.error("--length must be at least 16")
sal=['','MASTER','TEACHER','MY MASTER','MY TEACHER','DEAR MASTER','DEAR TEACHER','MY DEAR MASTER','MY DEAR TEACHER','WHITESMITH','DEAR WHITESMITH','MY FRIEND','DEAR FRIEND']
lead=[
'FORGIVE ME','PLEASE FORGIVE ME','I HOPE YOU CAN FORGIVE ME','I HOPE YOU WILL FORGIVE ME','I ASK YOUR FORGIVENESS',
'I AM SORRY','I AM SO SORRY','I AM DEEPLY SORRY','I MUST APOLOGIZE','I OWE YOU AN APOLOGY','DO NOT BE ANGRY','DO NOT THINK ME UNGRATEFUL',
'BY THE TIME YOU READ THIS','WHEN YOU READ THIS','IF YOU READ THIS','BY THE TIME YOU FIND THIS','WHEN YOU FIND THIS LETTER',
'I COULD NOT SAY GOODBYE','I COULD NOT FACE YOU','I COULD NOT TELL YOU','I COULD NOT WAIT','I COULD NOT STAY','I CANNOT STAY','I MUST LEAVE','I HAVE LEFT','I AM GONE',
'THANK YOU','I THANK YOU','I AM GRATEFUL','I WILL ALWAYS BE GRATEFUL','YOU HAVE BEEN KIND TO ME','YOU HAVE TAUGHT ME WELL',
'I HAVE TAKEN A NEEDLE','I HAVE TAKEN ONE NEEDLE','I HAVE TAKEN ONE OF YOUR NEEDLES','I TOOK ONE OF YOUR NEEDLES','I BORROWED ONE OF YOUR NEEDLES','I STOLE ONE OF YOUR NEEDLES',
'I AM GOING HOME','I HAVE GONE HOME','I AM RETURNING TO THE ARCHIVE','I HAVE RETURNED TO THE ARCHIVE','I MUST RETURN TO THE ARCHIVE','THE ARCHIVE IS MY CALLING',
'I WRITE TO SAY GOODBYE','I WRITE TO SAY FAREWELL','THIS IS MY FAREWELL','I LEAVE THIS SHORT LETTER','I LEAVE YOU THIS LETTER']
cont=[
'I WILL BE GONE','I WILL HAVE GONE','I WILL HAVE LEFT','I HAVE ALREADY LEFT','I AM ALREADY GONE','I MUST LEAVE','I HAD TO LEAVE','I COULD NOT STAY','I CANNOT STAY','I CHOSE TO LEAVE','I LEFT AT MIDNIGHT','I LEAVE AT MIDNIGHT',
'I HAVE GONE HOME','I AM GOING HOME','I MUST GO HOME','I HAVE LEFT THE WORKSHOP','I HAVE GONE TO THE ARCHIVE','I AM GOING TO THE ARCHIVE','I MUST RETURN TO THE ARCHIVE','I AM RETURNING TO THE ARCHIVE','I HAVE RETURNED TO THE ARCHIVE','I GO BACK TO THE ARCHIVE',
'I HAVE TAKEN A NEEDLE','I HAVE TAKEN ONE NEEDLE','I HAVE TAKEN ONE OF YOUR NEEDLES','I TOOK ONE NEEDLE','I TOOK ONE OF YOUR NEEDLES','I BORROWED A NEEDLE','I BORROWED ONE OF YOUR NEEDLES','I STOLE A NEEDLE','I STOLE ONE OF YOUR NEEDLES','THE NEEDLE IS WITH ME','I WILL RETURN THE NEEDLE',
'YOU SAID I COULD TAKE ONE','YOU SAID I COULD TAKE ONE OF MY OWN MAKING','YOU TOLD ME I COULD TAKE ONE','YOU TOLD ME I COULD TAKE ONE OF MY OWN MAKING','I KNOW IT IS NOT MINE','I KNOW THIS NEEDLE IS NOT MINE','I KNOW IT IS NOT OF MY OWN MAKING','I KNOW I HAVE NO RIGHT TO TAKE IT',
'I CANNOT WAIT TEN YEARS','I COULD NOT WAIT TEN YEARS','TEN YEARS IS TOO LONG','TEN YEARS WOULD BE TOO LONG','MY WORK CANNOT WAIT','THE KNOT CANNOT WAIT','THE KNOT AWAITS ME','THE ARCHIVE AWAITS ME','THE ARCHIVE CALLS ME','THE ARCHIVE IS MY TRUE CALLING','MY TRUE CALLING IS THE ARCHIVE',
'I MUST UNRAVEL THE KNOT','I MUST FINISH WHAT I BEGAN','I MUST COMPLETE MY WORK','I KNOW WHAT I MUST DO','I HAVE MADE MY CHOICE','MY CHOICE IS MADE','DO NOT FOLLOW ME','PLEASE DO NOT FOLLOW ME','DO NOT SEARCH FOR ME',
'I AM GRATEFUL TO YOU','I WILL ALWAYS BE GRATEFUL','I WILL NEVER FORGET YOU','I WILL NEVER FORGET YOUR LESSONS','YOU HAVE TAUGHT ME WELL','YOU HAVE BEEN A GOOD TEACHER','THANK YOU FOR YOUR PATIENCE','THANK YOU FOR ALL YOU HAVE TAUGHT ME','I OWE YOU EVERYTHING','I AM NOT UNGRATEFUL',
'BUT I MUST LEAVE','BUT I COULD NOT STAY','BUT I MUST GO HOME','BUT THE ARCHIVE CALLS ME','BUT THE KNOT AWAITS ME','PLEASE UNDERSTAND','I HOPE YOU UNDERSTAND','FAREWELL','GOODBYE']
connect=['','AND','BUT','FOR','BECAUSE','PLEASE KNOW THAT','I KNOW THAT']
def n(s):return re.sub('[^A-Z]','',s.upper())
out=set()
def add(s):
 s=n(s)
 if len(s)>=args.length:out.add(s[:args.length])
for a,b,c in itertools.product(sal,lead,cont):add(a+' '+b+' '+c)
for a,b,c in itertools.product(lead,connect,cont):add(a+' '+b+' '+c)
# Natural fixed constructions with object variants.
for who in ['MASTER','TEACHER','DEAR MASTER','DEAR TEACHER','MY DEAR TEACHER','']:
 for verb in ['FORGIVE ME','PLEASE FORGIVE ME','I AM SORRY']:
  for reason in ['FOR LEAVING WITHOUT SAYING GOODBYE','FOR TAKING ONE OF YOUR NEEDLES','I HAVE TAKEN ONE OF YOUR NEEDLES','I COULD NOT WAIT TEN YEARS','I MUST RETURN TO THE ARCHIVE']:
   add(f'{who} {verb} {reason}')
with open(args.output, 'w', encoding='ascii') as f:
 f.write('\n'.join(sorted(out))+'\n')
print(f'wrote {len(out)} cribs to {args.output}')
