PK9_REAL = "KSYAWFEYYOISZGEUFBLYATAIBYFAQBQYYVDWJKLJXMYIEPIFVHPQNHZGSUHUUDXLEHRHUMALHEGLHXSJMUXGNUIVBXGUJHZRZGUSVHMLSCTSUQXHSUMQQIFUQGKHJGUQGLHDKEWSKAMHIJXD"

print("The 28 slices of PK9 ciphertext:")
for k in range(28):
    sl = PK9_REAL[k::28]
    print(f"Slice {k:2d} (len {len(sl):1d}): {sl}")
