import subprocess

phrases = [
    "ANEEDLEOFMYOWNMAKING",
    "THENEEDLEOFMYOWNMAKING",
    "THELOSTARCHIVEOFPELLEGRIN",
    "LOSTARCHIVEOFPELLEGRIN",
    "ROUTE TOTHELOSTARCHIVEOF",
    "UNRAVELEDITREVEALSTHEROUTE",
    "ANEEDLESOTHINASTOREADANYKNOT",
    "NEEDLESOTHINASTOREADANYKNOT",
    "FORTENYEARSIWORKEDUNDERHIM",
    "AFTERTENYEARSISTUDIEDUNDER",
    "AFTERTENYEARSOFPRACTICE",
    "AFTERTENYEARSIFINISHED",
    "ATLASTTHENEEDLEWASFINISHED",
    "ATLASTTHENEEDLEOFMYOWNMAKING",
    "IRETURNEDTOTHELOSTARCHIVE",
    "IRETURNEDTOTHEARCHIVEWITH",
    "ITOKTHENEEDLEOFMYOWNMAKING",
    "ITOKTHENEEDLEANDUNRAVELED",
    "ITOKTHENEEDLEANDINSERTED",
    "UNRAVELEDTHEKNOTANDREAD",
    "THEKNOTBEGANTOUNRAVEL",
    "THELETTERSINSCRIBEDUPON",
    "THELETTERSINSCRIBEDONTHE",
    "INSCRIBEDWITHLETTERSTHE",
    "INVESTIGATIONLOGITEMNINE",
    "INVESTIGATIONLOGITEMTEN",
    "ACCESSIONLOGITEMNINE",
    "ACCESSIONLOGITEMTEN",
    "TWELVEPRIORARCHIVISTSTRIED",
    "UNRAVELITREVEALSTHEROUTETO",
    "PELLEGRINSWORKSHOPWASFOUND",
    "UNAGOTANTOSOTTILEDALEGGERE",
    "TANTOSOTTILEDALEGGEREQUALUNQUE",
    "LEGGEREQUALUNQUENODO",
    "SEVENTHMONTHIWROTETOFIFTEEN",
    "EIGHTHMONTHIWROTETOFIFTEEN",
    "NINTHMONTHIWROTETOFIFTEEN",
    "TENTHMONTHIWROTETOFIFTEEN",
    "ELEVENTHMONTHIWROTETOFIFTEEN",
    "TWELFTHMONTHIWROTETOFIFTEEN"
]

# Clean phrases
clean_phrases = []
for p in phrases:
    c = "".join(ch for ch in p.upper() if ch.isalpha())
    if len(c) >= 22:
        clean_phrases.append(c[:22])
        # also append other 22-char slices
        for s in range(len(c) - 21):
            clean_phrases.append(c[s:s+22])

clean_phrases = list(set(clean_phrases))
print(f"Generated {len(clean_phrases)} 22-character crib candidates from Dan Robinson's motifs.")

with open("dan_motifs_pk10.txt", "w") as f:
    for c in clean_phrases:
        f.write(c + "\n")

