"""Compile buttcrack's English corpus models into a compact browser model.

Reads the gzipped trigram counts and word frequencies that ship with the
package and emits ``model.js`` (~50 KB) holding quantised trigram log
probabilities plus the 4000 most common words. Re-run after updating the
corpus:  python3 ventures/cipher-solver-web/build_model.py
"""

from __future__ import annotations

import gzip
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "buttcrack" / "data"
OUT = Path(__file__).with_name("model.js")
B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
MIN_COUNT = 1500  # trigram cutoff: keeps ~4.7k grams, ~97% of corpus mass
MAX_WORDS = 4000


def main() -> None:
    tri: dict[str, int] = {}
    with gzip.open(DATA / "english_trigrams.txt.gz", "rt") as fh:
        for line in fh:
            gram, count = line.split()
            tri[gram] = int(count)

    total = sum(tri.values())
    kept = sorted(((g, c) for g, c in tri.items() if c >= MIN_COUNT), key=lambda kv: -kv[1])
    vals = [math.log10(c / total) for _, c in kept]
    lo, hi = min(vals), max(vals)
    floor = math.log10(0.01 / total)

    def quant(v: float) -> int:
        return min(255, max(0, round((v - lo) / (hi - lo) * 255)))

    packed = "".join(g + B64[(quant(v) >> 6) & 3] + B64[quant(v) & 63] for (g, _), v in zip(kept, vals))

    with gzip.open(DATA / "english_words.json.gz", "rt") as fh:
        words = json.load(fh)
    top = [w for w, _ in sorted(words.items(), key=lambda kv: -kv[1]) if w.isalpha() and 1 <= len(w) <= 12][
        :MAX_WORDS
    ]

    OUT.write_text(
        "/* Auto-generated by ventures/cipher-solver-web/build_model.py — do not edit.\n"
        " * Compiled from buttcrack's English corpus models (trigram counts + word list).\n"
        " * Packed as: 3 letters + 2 base64 chars of quantised log10 probability.\n"
        " */\n'use strict';\n"
        f"const TRI_LO = {lo:.6f}, TRI_HI = {hi:.6f}, TRI_FLOOR = {floor:.6f};\n"
        f'const TRI_PACKED = "{packed}";\n'
        f'const TOP_WORDS = "{" ".join(top)}";\n'
        "if (typeof module !== 'undefined' && module.exports)\n"
        "  module.exports = { TRI_LO, TRI_HI, TRI_FLOOR, TRI_PACKED, TOP_WORDS };\n"
    )
    print(f"wrote {OUT} — {len(kept)} trigrams, {len(top)} words, {OUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
