#!/usr/bin/env python3
"""Build the sample puzzles in ``examples/puzzles/``.

Every puzzle is generated by buttcrack's own cipher implementations from a
plaintext in ``examples/plaintexts.py``, so the answers are known by
construction and the set can be rebuilt after any change::

    python3 examples/generate.py            # rewrite the puzzles and ANSWERS.md
    python3 examples/generate.py --check    # regenerate and verify each one solves

``--check`` is what keeps the samples honest: a puzzle that the solver cannot
break with the budget printed next to it is a puzzle nobody should be handed.
"""

from __future__ import annotations

import argparse
import base64
import sys
import time
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from buttcrack import get, solve  # noqa: E402

OUT_DIR = Path(__file__).resolve().parent / "puzzles"

# Two paragraphs of ordinary English prose.  Long enough that the statistical
# attacks have something to measure, ordinary enough that nothing about the
# vocabulary hints at the key.
PROSE = (
    "The council of Venice has decreed that all merchant vessels must pay the new harbour tax "
    "before entering the lagoon, and the guild of mariners has protested to the doge in writing. "
    "Every secret society in the city maintains at least one archive of forbidden documents, and "
    "the committee has decided to postpone the railway conference until further notice is issued "
    "by the board of directors."
)
SHORT = "Meet the courier beside the fountain at noon and bring the second envelope."


def _layers(*encoders: Callable[[str], str]) -> Callable[[str], str]:
    def apply(text: str) -> str:
        for encoder in encoders:
            text = encoder(text)
        return text

    return apply


def b64(text: str) -> str:
    return base64.b64encode(text.encode()).decode()


def b16(text: str) -> str:
    return get("base16").encrypt(text)


def b32(text: str) -> str:
    return get("base32").encrypt(text)


def cipher(name: str, key: Any = None) -> Callable[[str], str]:
    target = get(name)
    used = target.info.example_key if key is None else key
    return lambda text: target.encrypt(text, used)


#: filename, difficulty, what the puzzle is, the builder, the true key, the
#: plaintext, and the budget ``--check`` allows.
PUZZLES: tuple[tuple[str, str, str, Callable[[str], str], str, str, float], ...] = (
    ("01-caesar", "easy", "A shift cipher over ordinary prose.", cipher("caesar", 7), "7", PROSE, 10),
    ("02-atbash", "easy", "The reciprocal alphabet.", cipher("atbash"), "none", PROSE, 10),
    ("03-vigenere", "easy", "A repeating keyword.", cipher("vigenere", "LANTERN"), "LANTERN", PROSE, 20),
    ("04-morse", "easy", "Morse code, spaces between letters.", cipher("morse"), "none", SHORT, 10),
    ("05-base64-caesar", "easy", "Base64 around a shift.", _layers(cipher("caesar", 11), b64), "11", PROSE, 15),
    ("06-columnar", "medium", "A columnar transposition: the letters are all there, in the wrong order.",
     cipher("columnar", "SPIES"), "SPIES", PROSE, 30),
    # The XOR ciphers already emit their payload as hex, so there is no base16
    # layer to add here: wrapping them again would produce a digits-only string,
    # which is genuinely ambiguous with decimal ASCII and the solver refuses to
    # guess between the two.
    ("07-hex-xor", "medium", "A repeating-key XOR over raw bytes; the payload arrives as hex.",
     cipher("xor_repeating", "LAMP"), "LAMP", PROSE, 30),
    ("08-rail-fence", "medium", "Rail fence, four rails.", cipher("rail_fence", 4), "4", PROSE, 20),
    ("09-affine", "medium", "A linear map: multiply by 5, add 8.", cipher("affine", {"a": 5, "b": 8}),
     "a=5, b=8", PROSE, 20),
    ("10-base32-base64", "medium", "Two encodings stacked, no cipher underneath.",
     _layers(b64, b32), "none", PROSE, 20),
    ("11-autokey", "hard", "An autokey: a short primer, then the plaintext itself as the key.",
     cipher("autokey", "PRIMER"), "PRIMER", PROSE, 40),
    ("12-substitution", "hard", "A keyword-mixed alphabet. Needs a real search.",
     cipher("keyword_substitution", "GALAXY"), "GALAXY", PROSE * 2, 90),
    ("13-three-layers", "hard", "Base64 around the hex payload of a repeating-key XOR: three "
     "layers deep, and the key belongs to the innermost one.",
     _layers(cipher("xor_repeating", "VENICE"), b64), "VENICE", PROSE, 40),
    ("14-bacon", "hard", "Bacon's A/B alphabet, then base32.",
     _layers(cipher("bacon"), b32), "none", SHORT, 30),
    ("15-playfair", "brutal", "A 5x5 grid. Expect most of the letters, not always all of them; "
     "`--hint key=MONARCHY` finishes it at once.",
     cipher("playfair", "MONARCHY"), "MONARCHY", PROSE * 3, 120),
)


def build() -> list[tuple[str, str, str, str, str, float]]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written: list[tuple[str, str, str, str, str, float]] = []
    for name, difficulty, blurb, make, key, plaintext, budget in PUZZLES:
        ciphertext = make(plaintext)
        path = OUT_DIR / f"{name}.txt"
        path.write_text(ciphertext + "\n", encoding="utf-8")
        written.append((name, difficulty, blurb, key, plaintext, budget))
        print(f"  wrote {path.relative_to(ROOT)} ({len(ciphertext)} characters)")
    write_answers(written)
    return written


def write_answers(written: list[tuple[str, str, str, str, str, float]]) -> None:
    lines = [
        "# Answers",
        "",
        "Generated by `examples/generate.py` -- the puzzles are built from these plaintexts with",
        "these keys, so the answers are known by construction rather than guessed.",
        "",
        "| puzzle | difficulty | key | budget | decode chain |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name, difficulty, _blurb, key, _plaintext, budget in written:
        chain = {
            "01-caesar": "caesar",
            "02-atbash": "atbash (may be reported as affine a=25,b=25)",
            "03-vigenere": "vigenere",
            "04-morse": "morse",
            "05-base64-caesar": "base64 -> caesar",
            "06-columnar": "columnar",
            "07-hex-xor": "base16 -> xor_repeating",
            "08-rail-fence": "rail_fence",
            "09-affine": "affine",
            "10-base32-base64": "base32 -> base64",
            "11-autokey": "autokey",
            "12-substitution": "keyword_substitution (or substitution)",
            "13-three-layers": "base64 -> base16 -> xor_repeating",
            "14-bacon": "base32 -> bacon",
            "15-playfair": "playfair",
        }.get(name, "")
        lines.append(f"| `{name}.txt` | {difficulty} | `{key}` | {budget:.0f}s | {chain} |")
    lines += [
        "",
        "The plaintext of the long puzzles:",
        "",
        "> " + PROSE,
        "",
        "The short ones (`04-morse`, `14-bacon`):",
        "",
        "> " + SHORT,
        "",
        "`12-substitution` uses that paragraph twice, and `15-playfair` three times: both need the",
        "length before the search has enough evidence to settle on one key.",
        "",
    ]
    (OUT_DIR / "ANSWERS.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {(OUT_DIR / 'ANSWERS.md').relative_to(ROOT)}")


def fold(text: str, name: str) -> str:
    """Squash a text for comparison, folding away what the cipher cannot return."""
    out = "".join(c for c in text.upper() if c.isalnum())
    if name.startswith("14-bacon"):
        out = out.replace("J", "I").replace("V", "U")
    if name.startswith(("14-bacon", "15-playfair")):
        out = out.replace("J", "I").replace("X", "")
    return out


def similarity(got: str, want: str) -> float:
    """Sequence similarity, which survives the X-padding offsets Playfair leaves."""
    import difflib

    return difflib.SequenceMatcher(None, got, want, autojunk=False).ratio() if got and want else 0.0


def check() -> int:
    """Solve every puzzle with no hints and report what came back."""
    failures = 0
    for name, difficulty, _blurb, _make, key, plaintext, budget in PUZZLES:
        path = OUT_DIR / f"{name}.txt"
        if not path.is_file():
            print(f"  MISSING {name}: run `python3 examples/generate.py` first")
            failures += 1
            continue
        started = time.time()
        ciphertext = path.read_text(encoding="utf-8")
        report = solve(ciphertext, budget=budget, workers=2)
        want = fold(plaintext, name)
        got = fold(report.plaintext, name)
        if name == "15-playfair":
            # Documented as partial.  A 25-cell grid in pure Python is a coin
            # toss: measured confidence for this exact puzzle ranges from 0.08 to
            # 0.66 across seeds and worker counts.  So the unhinted run is
            # reported and not graded, and what *is* graded is the contract --
            # the cipher is named, and handing over the key finishes it at once.
            ratio = similarity(got, want)
            hinted = solve(ciphertext, budget=30, workers=2, hints={"key": key})
            ok = (
                report.cipher == "playfair"
                and hinted.solved
                and fold(hinted.plaintext, name) == want
            )
            detail = (
                f"unhinted {report.confidence:.3f} ({ratio * 100:.0f}% of the message), "
                f"hinted {hinted.confidence:.3f} exact={fold(hinted.plaintext, name) == want}"
            )
        else:
            ok = report.solved and got == want
            detail = f"{report.confidence:.3f} via {report.path}"
        print(f"  {'pass' if ok else 'FAIL'}  {name:<20} {difficulty:<7} key={key:<12} {detail} in {time.time() - started:.1f}s")
        failures += 0 if ok else 1
    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="solve every puzzle and report")
    args = parser.parse_args(argv)
    if args.check:
        failures = check()
        print(f"\n{len(PUZZLES) - failures}/{len(PUZZLES)} puzzles solved as documented")
        return 1 if failures else 0
    build()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
