#!/usr/bin/env python3
"""Build the shared, verified Paradigm Kryptos PK1–PK10 catalog.

The recovered corpus is maintained in ``kryptos/pk_submission_manifest.json``.
Buttcrack has two independently shipped front ends: the packaged Python desktop
application and the zero-server browser solver.  This small generator makes both
consume the same normalized records, so a corrected challenge transcription
cannot drift into one surface but not the other.

Run after changing the submission manifest::

    python3 scripts/build_paradigm_catalog.py

It writes only committed source assets; it never contacts a network service.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "kryptos" / "pk_submission_manifest.json"
PYTHON_DATA = ROOT / "buttcrack" / "data" / "paradigm_kryptos.json"
BROWSER_ASSETS = (
    ROOT / "buttcrack" / "static" / "paradigm.js",
    ROOT / "ventures" / "cipher-solver-web" / "paradigm.js",
)


def normalized_records(manifest: dict[str, Any]) -> list[dict[str, str | int]]:
    """Keep the front ends' catalog deliberately small and presentation-safe."""
    records: list[dict[str, str | int]] = []
    for number in range(1, 11):
        challenge_id = f"PK{number}"
        item = manifest[challenge_id]
        if item.get("status") != "SOLVED":
            raise SystemExit(f"{challenge_id} is not marked SOLVED in {SOURCE}")
        ciphertext = str(item["ciphertext"])
        plaintext = str(item["plaintext"])
        if not ciphertext.isalpha() or not plaintext.isalpha():
            raise SystemExit(f"{challenge_id} must contain normalized alphabetic text")
        records.append(
            {
                "id": challenge_id,
                "title": str(item["title"]),
                "mechanism": str(item["cipher_mechanism"]),
                "key": str(item["key"]),
                "ciphertext": ciphertext,
                "plaintext": plaintext,
                "ciphertext_length": len(ciphertext),
                "plaintext_length": len(plaintext),
                "plaintext_sha256": str(item["sha256"]),
                "verification": str(item["verification"]),
            }
        )
    return records


def javascript(records: list[dict[str, str | int]]) -> str:
    """A no-dependency browser lookup; also loaded inside the Web Worker."""
    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    return f'''/* Generated by scripts/build_paradigm_catalog.py; do not edit by hand.
 * Canonical, exact-match catalog for the recovered Paradigm Kryptos PK1–PK10
 * corpus.  It recognizes only a normalized ciphertext equality; it is not a
 * claim that arbitrary same-length text has been cryptanalysed. */
'use strict';

const PARADIGM_KRYPTOS = Object.freeze({payload}.map(Object.freeze));

function normaliseParadigmKryptos(text) {{
  return String(text || '').toUpperCase().replace(/[^A-Z]/g, '');
}}

function matchParadigmKryptos(text) {{
  const normalized = normaliseParadigmKryptos(text);
  return PARADIGM_KRYPTOS.find(record => record.ciphertext === normalized) || null;
}}

function knownParadigmResult(text) {{
  const record = matchParadigmKryptos(text);
  if (!record) return null;
  return {{
    cipher: `paradigm_kryptos_${{record.id.toLowerCase()}}`,
    key: record.key,
    plaintext: record.plaintext,
    confidence: 1,
    verified: true,
    paradigm: record,
    method: 'exact canonical-corpus match; recovered construction verified locally',
    verification: record.verification,
  }};
}}

if (typeof module !== 'undefined' && module.exports) {{
  module.exports = {{ PARADIGM_KRYPTOS, normaliseParadigmKryptos, matchParadigmKryptos, knownParadigmResult }};
}}
'''


def build() -> list[dict[str, str | int]]:
    manifest = json.loads(SOURCE.read_text(encoding="utf-8"))
    records = normalized_records(manifest)
    serialized = json.dumps(records, ensure_ascii=False, indent=2) + "\n"
    PYTHON_DATA.write_text(serialized, encoding="utf-8")
    script = javascript(records)
    for target in BROWSER_ASSETS:
        target.write_text(script, encoding="utf-8")
    return records


def main() -> int:
    records = build()
    print(f"wrote {len(records)} verified Paradigm Kryptos records")
    for record in records:
        print(f"  {record['id']}: {record['ciphertext_length']} ciphertext letters")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
