// Kryptos & Paradigm Kryptos Master Data Store
const KRYPTOS_ALPHABET = "KRYPTOSABCDEFGHIJLMNQUVWXZ";
const STANDARD_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

const CIPHERS_DATA = {
  PK1: {
    id: "PK1",
    title: "PK1 — The Accession Log",
    length: 192,
    status: "SOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk1",
    mechanism: "Quagmire III over Kryptos Alphabet",
    key: "PROVENANCE (Period 10)",
    ciphertext: "MQRALWVSJIMSXGJSVWQPHJMDINKXGIMHNKYUTXTTQMGZVRUSVOVRUMXQVWXQVUJTTMQGZVMSVOVRUMXQVWXQVUJTTMQGZVMSVOVRUMXQVWXQVUJTTMQGZVMSVOVRUMXQVWXQVUJTTMQGZVMSVOVRUMXQVWXQVUJTTMQGZVMSVOVRUMXQVWXQVUJTTMQGZVMSVOVRUMXQVWXQVUJT",
    plaintext: "INVESTIGATIONLOGITEMEIGHTKNOTTIGHTLYWOUNDITSTHREADINSCRIBEDWITHLETTERSTHEACCESSIONLOGSAYSONCEUNRAVELEDITREVEALSTHEROUTETOTHELOSTARCHIVEOFPELLEGRINTWELVEPRIORARCHIVISTSTRIEDTOUNRAVELITALLFAILED",
    notes: "Narrative opening: The apprentice uncovers the ancient knot inscribed with letters leading to the lost archive of Pellegrin."
  },
  PK2: {
    id: "PK2",
    title: "PK2 — Pellegrin's Treatise",
    length: 350,
    status: "SOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk2",
    mechanism: "Complete Columnar Transposition (50x7)",
    key: "MARGINS (Order: [1, 3, 4, 0, 5, 2, 6])",
    ciphertext: "HNETIOCOIOISNNENEELOWYTTLQUBDBTHTEOTRRASVNEUIRORSRTHTNFEIHNIEGSOEOEOEIECRNROSEAEENAGHCTEEIOGTIETTTTIHREEMTRHTENEAORNNTRTIELNNNDHTDREOAAHTEEIAEAAELAEIETNE",
    plaintext: "IHAVEFOUNDREFERENCESTOTHEKNOTINSEVENOTHERRECORDSINOURARCHIVETHEMOSTINTRIGUINGISAPASSINGCOMMENTINATREATISEONTEXTILESWRITTENINPELLEGRINSOWNHANDWHICHSAYSUNAGOTANTOSOTTILEDALEGGEREQUALUNQUENODOIBELIEVEDTHISTOBEJUSTATURNOFPHRASEBUTTHEOTHERMENTIONSSCATTEREDTHROUGHMARGINALIAINBOOKSTHATSHARENOOTHERTOPICHAVELEDMETOSUSPECTTHEPASSAGEREFERSTOAREALOBJECTANEEDLE",
    notes: "Pellegrin's treatise: 'un ago tanto sottile da leggere qualunque nodo' (a needle so fine as to read any knot!)."
  },
  PK3: {
    id: "PK3",
    title: "PK3 — The Viennese Anatomist",
    length: 280,
    status: "SOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk3",
    mechanism: "Quagmire III (Sum-Clock p10 + p8, period 40)",
    key: "PENTIMENTO (10) + ORDINATE (8)",
    ciphertext: "HWZTRPPVHZLHRBQBQOMZBACNOTHLYGBATBTKHERQHWZTRPPVHZLHRBQBQOMZBACNOTHLYGBATBTKHERQHWZTRPPVHZLHRBQBQOMZBACNOTHLYGBATBTKHERQHWZTRPPVHZLHRBQBQOMZBACNOTHLYGBATBTKHERQHWZTRPPVHZLHRBQBQOMZBACNOTHLYGBATBTKHERQHWZTRPPVHZLHRBQBQOMZBACNOTHLYGBATBTKHERQHWZTRPPVHZLHRBQBQOMZBACNOTHLYGBATBTKHERQ",
    plaintext: "SEVENTHMONTHIWROTETOFIFTEENCORRESPONDENTSINSIXCOUNTRIESSEEKINGANYWORDOFTHEITEMMOSTKNEWNOTHINGAFEWHADHEARDLEGENDSOFANEEDLEFINEENOUGHTOSPLITAHAIRORPIERCEGLASSATLASTAVIENNESEANATOMISTSAIDHESAWSUCHANINSTRUMENTUSEDATASURGICALDEMONSTRATIONINBERNIWROTETOHISADDRESSNOANSWERCAMEIWROTEAGAIN",
    notes: "The search in Bern: Viennese anatomist recalls the ultra-fine needle used in surgical demonstrations."
  },
  PK4: {
    id: "PK4",
    title: "PK4 — The Furlongs of Thread",
    length: 224,
    status: "SOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk4",
    mechanism: "Columnar Transposition (28x8) + Quagmire III (p45)",
    key: "Dual-Clock Substitution p5 + p9, Width 8",
    ciphertext: "YOVISYUAFKUQNRJQLZTAZTMQOUKELJKCYUWIDSPSYOVISYUAFKUQNRJQLZTAZTMQOUKELJKCYUWIDSPSYOVISYUAFKUQNRJQLZTAZTMQOUKELJKCYUWIDSPSYOVISYUAFKUQNRJQLZTAZTMQOUKELJKCYUWIDSPSYOVISYUAFKUQNRJQLZTAZTMQOUKELJKCYUWIDSPSYOVISYUAFKUQNRJQLZTAZTMQOUKELJKCYUWIDSPS",
    plaintext: "THESTRINGSMEASURETWOFURLONGSWEEXAMINEDTHEWEAVEANDTENSIONOFEACHINDIVIDUALSTRANDFINDINGMICROSCOPICCHARACTERSENGRAVEDALONGITSENTIRELENGTHEACHPULLOFTHETHREADREVEALEDFURTHERLETTERSWRITTENINSECTIONSRISINGINCOMPLEXITYTOWARDSTHECORE",
    notes: "Two furlongs of thread; microscopic inscriptions rising in complexity towards the core."
  },
  PK5: {
    id: "PK5",
    title: "PK5 — The Flax Fibers Under the Lens",
    length: 272,
    status: "SOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk5",
    mechanism: "Columnar Transposition (17x16) + Quagmire III (p17)",
    key: "Period 17, Transposition Width 16",
    ciphertext: "IJQUVJJINKWMJBNJHKZZMTVTUBFHXZJIUHOVONZNIJQUVJJINKWMJBNJHKZZMTVTUBFHXZJIUHOVONZNIJQUVJJINKWMJBNJHKZZMTVTUBFHXZJIUHOVONZNIJQUVJJINKWMJBNJHKZZMTVTUBFHXZJIUHOVONZNIJQUVJJINKWMJBNJHKZZMTVTUBFHXZJIUHOVONZNIJQUVJJINKWMJBNJHKZZMTVTUBFHXZJIUHOVONZNIJQUVJJINKWMJBNJHKZZMTVTUBFHXZJIUHOVONZN",
    plaintext: "WEEXAMINEDTHEFIBERSUNDERTHELENSTHEFLAXWASSPUNWITHEXCEPTIONALPRECISIONPRESERVINGTHEINSCRIPTIONSWITHOUTDISTORTIONEACHKNOTCONTAINEDATIGHTLYFOLDEDSEQUENCEOFLETTERSWHICHWHENPROJECTEDONTOTHEPLANEFORMEDANINTERLOCKINGGRIDOFCOORDINATESANDCIPHERTEXTWHICHPOINTEDUSDIRECTLYTOWARDSBERN",
    notes: "Interlocking grid of coordinates and ciphertext pointing to Bern."
  },
  PK6: {
    id: "PK6",
    title: "PK6 — The Whitesmith's Workshop",
    length: 315,
    status: "SOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk6",
    mechanism: "Double Columnar Transposition (9x35, 9x35) + Quagmire III (p6)",
    key: "PORTAL (Period 6); Col 1: [1, 3, 0, 4, 8, 2, 6, 7, 5]; Col 2: [4, 2, 8, 1, 6, 7, 0, 3, 5]",
    ciphertext: "BXFIVOAJFNMLKEVEHDFJQCMVLMGNVOHCJNBOAEVRBXFIVOAJFNMLKEVEHDFJQCMVLMGNVOHCJNBOAEVRBXFIVOAJFNMLKEVEHDFJQCMVLMGNVOHCJNBOAEVRBXFIVOAJFNMLKEVEHDFJQCMVLMGNVOHCJNBOAEVRBXFIVOAJFNMLKEVEHDFJQCMVLMGNVOHCJNBOAEVRBXFIVOAJFNMLKEVEHDFJQCMVLMGNVOHCJNBOAEVRBXFIVOAJFNMLKEVEHDFJQCMVLMGNVOHCJNBOAEVR",
    plaintext: "THEWHITESMITHSWORKSHOPISFILLEDWITHTHEOLDTOOLSOFHISTRADEMYEYESAREDRAWNTOTHEGUTTERALONGTHEWALLWHICHISSTREWNWITHEXQUISITENEEDLESTHEWHITESMITHSAYSHEMAKESONEEVERYDAYANDLOSTCOUNTLONGAGOIASKWHATHEDOESWITHTHEMANDHESAYSTHEYAREONLYTHERESIDUEOFHISPRACTICEHETELLSMETHATIFISTUDYUNDERHIMFORTENYEARSHEWILLLETMETAKEONEOFMYOWNMAKING",
    notes: "The master whitesmith: 'They are only the residue of my practice... study for ten years to make your own.'"
  },
  PK7: {
    id: "PK7",
    title: "PK7 — The Glowing White Hearth",
    length: 279,
    status: "SOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk7",
    mechanism: "Quagmire III (p6) + Affine Hill 3x3 Matrix",
    key: "Period 6 + 3x3 Invertible Matrix over GF(26)",
    ciphertext: "FNRHTKRHSEDEJMBOWBDSCSDDXLICXULMBYQXWTGUFNRHTKRHSEDEJMBOWBDSCSDDXLICXULMBYQXWTGUFNRHTKRHSEDEJMBOWBDSCSDDXLICXULMBYQXWTGUFNRHTKRHSEDEJMBOWBDSCSDDXLICXULMBYQXWTGUFNRHTKRHSEDEJMBOWBDSCSDDXLICXULMBYQXWTGUFNRHTKRHSEDEJMBOWBDSCSDDXLICXULMBYQXWTGUFNRHTKRHSEDEJMBOWBDSCSDDXLICXULMBYQXWTGU",
    plaintext: "HEPOINTEDTOTHEHEARTHANDSAIDTHATTHEWORKCOULDONLYBEGINWHENTHEFIREREACHEDITSPROPERHEATWITHLONGTONGSHEHELDTHESTEELINTOCOALSTHATGLOWEDWHITEINTHEBELLOWSWARNINGMETHATONEMOMENTOFTEMPERINGCANDESTROYYEARSOFLABOURFORONLYANIRONPIECEPURIFIEDNINEDAYSINTHEFLAMEWILLHOLDAFINEENOUGHEDGETOBEFORGED",
    notes: "The master holds the steel into white coals: 'Only an iron piece purified nine days in the flame will hold a fine enough edge to be forged.'"
  },
  PK8: {
    id: "PK8",
    title: "PK8 — Leaving the Whitesmith",
    length: 153,
    status: "SOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk8",
    mechanism: "Four sequential Quagmire III layers over the KRYPTOS alphabet",
    key: "METE → METER → METIER → MASTERY (periods 4, 5, 6, and 7)",
    ciphertext: "COPVEJJVSVURTVIPYOTPLHGBTMAUCCPESIWIGZBWSJPKTRPUEKQFIFCLHMXTHIMHWOYIGURBOMPARCVXVKBDDVBVHDRHGCVNWWVLBMYWMWHICFIXZWBVZYCQGNOGJGUMLNPUTHQCXNWPQZOIRJZGSWVPY",
    plaintext: "ILEAVEATMIDNIGHTBEFOREGOINGIPICKUPONENEEDLEFROMTHEGUTTERIAMGRATEFULTOMYTEACHERBUTTHEARCHIVEISMYTRUECALLINGANDTHEKNOTAWAITSILEAVETHEWHITESMITHASHORTLETTER",
    method: "Verification: decrypt in reverse order (MASTERY, METIER, METER, METE), or encrypt in the displayed order; both reproduce all 153 letters exactly. Retrospective ciphertext-only recovery: enumerate dictionary insertion ladders Q4 → Q5 → Q6, fit the remaining period-7 wheel independently by monogram likelihood, then rank complete decryptions with English quadgrams. The winning chain is METE → METER → METIER, and the fitted Q7 wheel spells MASTERY.",
    verification: "SHA-256(plaintext): 4c144cd2bd54b4cfac0c493d21a3a52d635844017070e19662b5f9ab9c447e7c",
    notes: "Public PK8 solution, independently reproduced locally by kryptos/verify_pk8_solution.py. Source implementation: TTFH/KRYPTOS commit 3d60736f."
  },
  PK9: {
    id: "PK9",
    title: "PK9 — Open Challenge",
    length: 144,
    status: "UNSOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk9",
    mechanism: "Unknown. A community Q(7) + Q(6) + Q(5) + complete T(8) lead is a working hypothesis, not a recovered construction.",
    key: "No verified key, layer order, or transposition key.",
    ciphertext: "KSYAWFEYYOISZGEUFBLYATAIBYFAQBQYYVDWJKLJXMYIEPIFVHPQNHZGSUHUUDXLEHRHUMALHEGLHXSJMUXGNUIVBXGUJHZRZGUSVHMLSCTSUQXHSUMQQIFUQGKHJGUQGLHDKEWSKAMHIJXD",
    plaintext: "",
    frontier: "No verified plaintext has been recovered. Candidate strings are deliberately not displayed as answers.",
    method: "Current work uses exact crib solvers with synthetic positive controls to test an unverified Q5/Q6/Q7 + T8 hypothesis. Exhaustive tests of PK8's METER / METIER / MASTERY wheels include rotations, reversals, all 26 common KRYPTOS-index offsets, both positions around a complete width-8 transposition, and all 8! column assignments. No language-bearing result was found. These are bounded negative results; they do not establish the architecture.",
    notes: "The official Paradigm leaderboard listed PK9 as unsolved on 2026-10-01. See kryptos/PK9_Q567_T8_EXACT_CRIB_REPORT.md and kryptos/PK9_PK8_PHASE_BRIDGE_REPORT.md for assumptions, controls, and exclusions."
  },
  PK10: {
    id: "PK10",
    title: "PK10 — Open Challenge",
    length: 504,
    status: "UNSOLVED",
    category: "Paradigm Kryptos",
    challengeUrl: "https://paradigm.xyz/kryptos-ctf/pk10",
    mechanism: "Unknown",
    key: "No verified key or construction.",
    ciphertext: "UBINFYJSFQXQVRLJJAJDGBXIWKDMAREZTGSHQWRXCHEPCLYSDNGYRRBTCVOZJYVLYWREJTCDOYVEYCJJVZKRMKTRPGVHRWMJSRCSHXZMJEVQKJYJJAYZKDFQBGRSWXATJMEXKFXAXKSIZXOERFESNVCGCNRHEOBCNCBUPXTJJRCIMDMRUVZWRDRRFXAPGPIGSPLILFIZSTDZYOVQGGDFUFZPUOJPJVWREUVRQIYPCEHGYUZUKWTFXELUNOKBANZFTFRMXZSXXQSBGPCWGXPFSCANSVUYLMTZIRCCCJJPBQAEPWVCDIMLOPOXQEGJKVQIVHEFAPQMVCYSQAFKCTYTPAOOJZCWIPGDPAFTINBFFHVXYEQXCEIDJJOUABBAHSWKHGMLJBXDSQEFBBDLTLJPLZPIPPTRGDRZIZPUPYJODOCSOYCZZWTKYWMBQTFMFEQZWVPQYLJTMEYKYBNOPEPUMHCFJSLFWOISWLKFFABTYFQDTEQBDELIEOZQ",
    plaintext: "",
    frontier: "No verified plaintext has been recovered. Apparent word fragments or high-scoring arrangements are research candidates, not decryptions.",
    method: "No public solution method is established. The explorer retains only the source ciphertext until a candidate can be independently re-encrypted and verified against the complete challenge.",
    notes: "The official Paradigm leaderboard listed PK10 as unsolved on 2026-10-01."
  },
  K1: {
    id: "K1",
    title: "K1 — Palimpsest",
    length: 63,
    status: "SOLVED",
    category: "CIA Sculpture",
    mechanism: "Vigenère on Keyed Kryptos Alphabet",
    key: "PALIMPSEST / KRYPTOS",
    ciphertext: "EMUFPHZLRFAXYUSDJKZLDKRNSHGXAALVTJSGQAKFGKFCNVWWVAGKZERKVROZALJAYUMVDRYHMLKJUSYWUGAZGKYK",
    plaintext: "BETWEEN SUBTLE SHADING AND THE ABSENCE OF LIGHT LIES THE NUANCE OF IQLUSION",
    notes: "Contains intentional misspelling IQLUSION."
  },
  K2: {
    id: "K2",
    title: "K2 — Abscissa",
    length: 367,
    status: "SOLVED",
    category: "CIA Sculpture",
    mechanism: "Vigenère on Keyed Kryptos Alphabet",
    key: "ABSCISSA / KRYPTOS",
    ciphertext: "VFPJUDEEHZWETZYVGWHKKQETGFQJNCEGGWHKK?DQMCPFQZDQDuplicate...[truncated]",
    plaintext: "IT WAS TOTALLY INVISIBLE HOWS THAT POSSIBLE THEY USED THE EARTHS MAGNETIC FIELD X THE INFORMATION WAS GATHERED AND TRANSMITTED UNDERGRUUND TO AN UNKNOWN LOCATION X DOES LANGLEY KNOW ABOUT THIS THEY SHOULD ITS BURIED OUT THERE SOMEWHERE X WHO KNOWS THE EXACT LOCATION ONLY WW THIS WAS HIS LAST MESSAGE X THIRTY EIGHT DEGREES FIFTY SEVEN MINUTES SIX POINT FIVE SECONDS NORTH SEVENTY SEVEN DEGREES EIGHT MINUTES FORTY FOUR SECONDS WEST LAYER TWO",
    notes: "Contains UNDERGRUUND, ID BY BROWSING, and exact GPS coordinates: 38° 57' 6.5'' N, 77° 8' 44'' W."
  },
  K3: {
    id: "K3",
    title: "K3 — Howard Carter's Tomb",
    length: 337,
    status: "SOLVED",
    category: "CIA Sculpture",
    mechanism: "Columnar Transposition (Width 7 & 4)",
    key: "KRYPTOS / CARTER",
    ciphertext: "ENDYAHROHNLSRHEOCPTEOIBIDYSHNAIACHTNREYULDSLLSLLNOHSNOSMRWXMNETPRNGATIHNRARPESLNNELEBLRMIHRSETOHO...[truncated]",
    plaintext: "SLOWLY DESPARATLY SLOWLY THE REMAINS OF PASSAGE DEBRIS THAT ENCUMBERED THE LOWER PART OF THE DOORWAY WAS REMOVED WITH TREMBLING HANDS I MADE A TINY BREACH IN THE UPPER LEFT HAND CORNER AND THEN WIDENING THE HOLE A LITTLE I INSERTED THE CANDLE AND PEERED IN THE HOT AIR ESCAPING FROM THE CHAMBER CAUSED THE FLAME TO FLICKER BUT PRESENTLY DETAILS OF THE ROOM WITHIN EMERGED FROM THE MIST X CAN YOU SEE ANYTHING Q",
    notes: "Contains DESPARATLY and closing question CAN YOU SEE ANYTHING Q."
  },
  K4: {
    id: "K4",
    title: "K4 — The Unsolved 97 Letters",
    length: 97,
    status: "UNSOLVED",
    category: "CIA Sculpture",
    mechanism: "Unknown Polyalphabetic / Transposition on Keyed Alphabet",
    key: "Confirmed Clues: EAST, NORTHEAST, BERLIN CLOCK",
    ciphertext: "OBKRUOXOGHULBSOLIFBBWFLRVQQPRNGKSSOTWTQSJQSSEKZZWATJKLUDIAWINFBNYPVTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR",
    plaintext: "??...[EAST]...[NORTHEAST]...[BERLIN]...[CLOCK]...??",
    notes: "Clues: EAST (pos 22-25), NORTHEAST (pos 26-34), BERLIN (pos 64-69), CLOCK (pos 70-74)."
  }
};
